CREATE DATABASE va;
use va;

CREATE TABLE vacina (
  id INT AUTO_INCREMENT,
  nome VARCHAR(100),
  validade TIMESTAMP DEFAULT DATE_ADD(CURDATE(), INTERVAL 1 YEAR),
  PRIMARY KEY(id),
  UNIQUE (nome)
);

CREATE TABLE usuario (
  id INT AUTO_INCREMENT,
  nome VARCHAR(230),
  CPF CHAR(11),
  PRIMARY KEY (id),
  UNIQUE (CPF)
)

CREATE TABLE aplicador (
  id INT AUTO_INCREMENT,
  nome VARCHAR(230),
  CPF CHAR(11),
  PRIMARY KEY (id),
  UNIQUE (CPF)
)